# Define a dedicated namespace for all e-commerce microservices
apiVersion: v1               # Core API version for Kubernetes objects
kind: Namespace              # Declare this object as a Namespace
metadata:
  name: ecommerce            # Set the namespace name to 'ecommerce'
  labels:                    # Define labels for this namespace
    istio-injection: enabled # Enable automatic sidecar (Envoy proxy) injection by Istio
