# Define a dedicated namespace for all e-commerce microservices
apiVersion: v1              # Core API group version
kind: Namespace             # Namespace object
metadata:
  name: ecommerce           # Name of the namespace to isolate resources
