# Deployment and Service for shipping-service
apiVersion: apps/v1            # apps/v1 API
kind: Deployment               # Deployment
metadata:
  name: shipping-service       # Name of deployment
  namespace: ecommerce         # Namespace to deploy into
spec:
  replicas: 1                  # One pod
  selector:
    matchLabels:
      app: shipping-service    # Label selector
  template:
    metadata:
      labels:
        app: shipping-service  # Label on pods
      annotations:
        sidecar.istio.io/inject: "false" # Disable Istio injection
    spec:
      containers:
      - name: shipping-service # Container name
        image: ghcr.io/saputrauta/shipping-service:latest  # GitHub image
        ports:
        - containerPort: 3001  # Service listens on port 3001
        env:
        - name: PORT
          value: "3001"        # Use same .env port
        - name: AMQP_URL
          value: "amqp://rabbitmq:5672"  # RabbitMQ address
---
# Internal service to expose shipping-service
apiVersion: v1                 # Core API
kind: Service                  # Service object
metadata:
  name: shipping-service       # Service name
  namespace: ecommerce         # Same namespace
spec:
  selector:
    app: shipping-service      # Select pods with this label
  ports:
    - name: http               # Name the port
      port: 3001               # Port to expose
      targetPort: 3001         # Map to container port
